language: java
jdk:
  - oraclejdk8

install: ant

notifications:
  email:
    - gianbelinche@hotmail.com.ar
    - francobarreneche5@gmail.com
    - guido_botta@hotmail.com
    - julianv6004@gmail.com
